apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  labels:
    app: binarycalculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - name: binarycalculator
          image: northamerica-northeast2-docker.pkg.dev/lab3part1-452321/sofe3980u/binarycalculator:latest 
          ports:
            - containerPort: 8080
